{% set name = "riskmatrix" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a06e611a13746230f925d04e9e04cb0f9f5ab3ce0262774cdaa1b7da4edb5043

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7

test:
  imports:
    - riskmatrix

about:
  home: https://github.com/slicerisk/riskmatrix
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'A library to deal with risk matrix data.'
  doc_url: https://riskmatrix.readthedocs.io/
  dev_url: https://github.com/slicerisk/riskmatrix

extra:
  recipe-maintainers:
    - lonkeknol
